[web]
web-server ansible_host=54.177.219.251 ansible_user=ubuntu ansible_ssh_private_key_file=/mnt/c/Users/ghans/project/herovired/Assignment/TravelMemory/ansible/ghanshyam_b14.pem

[db]
db-server ansible_host=10.0.2.128 ansible_user=ubuntu ansible_ssh_private_key_file=/mnt/c/Users/ghans/project/herovired/Assignment/TravelMemory/ansible/ghanshyam_b14.pem ansible_ssh_common_args='-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o ProxyCommand="ssh -W %h:%p -q -i /mnt/c/Users/ghans/project/herovired/Assignment/TravelMemory/ansible/ghanshyam_b14.pem ubuntu@54.177.219.251"'

[all:vars]
ansible_python_interpreter=/usr/bin/python3
